name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install pip
      run:
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
    - name: Install poetry
      run: python -m pip install poetry
    - name: Install dependencies
      run: python -m poetry install
    - name: Pylint
      run: python -m pylint --reports=y --output-format=colorized --jobs=0 ./**/*.py
    - name: Black
      run: python -m black --check --diff --color ./**/*.py
