# https://github.com/github/super-linter
name: Lint Code Base

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_PYLINT: true
